/**
 * Azure Functions OpenAPI Extension
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { BoundingRect } from './boundingRect';
import { ObjectHierarchy } from './objectHierarchy';


export interface DetectedObject { 
    rectangle?: BoundingRect;
    object?: string;
    confidence?: number;
    parent?: ObjectHierarchy;
}

