/**
 * Azure Functions OpenAPI Extension
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ImageTag } from './imageTag';
import { Category } from './category';
import { FaceDescription } from './faceDescription';
import { ImageMetadata } from './imageMetadata';
import { AdultInfo } from './adultInfo';
import { DetectedObject } from './detectedObject';
import { DetectedBrand } from './detectedBrand';
import { ColorInfo } from './colorInfo';
import { ImageDescriptionDetails } from './imageDescriptionDetails';
import { ImageType } from './imageType';


export interface ImageAnalysis { 
    categories?: Array<Category>;
    adult?: AdultInfo;
    color?: ColorInfo;
    imageType?: ImageType;
    tags?: Array<ImageTag>;
    description?: ImageDescriptionDetails;
    faces?: Array<FaceDescription>;
    objects?: Array<DetectedObject>;
    brands?: Array<DetectedBrand>;
    requestId?: string;
    metadata?: ImageMetadata;
    modelVersion?: string;
}

